
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-main
  namespace: n8n-homol
spec:
  replicas: 1
  volumeClaimTemplates: []   # remove PVC
  template:
    spec:
      volumes: null          # remove volumes
      containers:
        - name: n8n
          envFrom: null      # remove secrets de prod
          volumeMounts: null # remove montagem de PVC
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_EXECUTIONS_MODE
              value: "regular"
            - name: DB_TYPE
              value: "sqlite"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_HOST
              value: "n8n-homol.129-213-28-76.sslip.io"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n-homol.129-213-28-76.sslip.io"
            - name: WEBHOOK_URL
              value: "https://n8n-homol.129-213-28-76.sslip.io/"

