apiVersion: v1
kind: Service
metadata:
  name: n8n-hs
  namespace: n8n        # <--- ADICIONE ISSO AQUI
  labels:
    app: n8n
    role: main
spec:
  clusterIP: None
  publishNotReadyAddresses: true  # Pode manter! É bom para StatefulSets.
  selector:
    app: n8n
    role: main
  ports:
    - name: http
      port: 5678
      targetPort: 5678
