apiVersion: v1
kind: Service
metadata:
  name: n8n-redis-hs
  labels:
    app: n8n-redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: n8n-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
