apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres-hs
  labels:
    app: n8n-postgres
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: n8n-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
