apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-redis
spec:
  serviceName: n8n-redis-hs
  replicas: 1
  selector:
    matchLabels:
      app: n8n-redis
  template:
    metadata:
      labels:
        app: n8n-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command: ["redis-server", "--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
